[versions]
agp = "9.3.1"
xdl = "2.4.0"
aih = "2.0.1"

[libraries]
xdl = { group = "io.github.hexhacking", name = "xdl", version.ref = "xdl" }
aih = { group = "com.bytedance.android", name = "shadowhook", version.ref = "aih" }

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
